version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
  build: ./server
  ports:
    - "5000:5000"
  env_file:
    - ./server/.env
