version: '3.8'

services:
  frontend:
    build: ./client
    container_name: frontend_jenkins
    ports:
      - "3001:80"
    volumes:
      - ./client:/app/client

  backend:
    build: ./server
    container_name: backend_jenkins
    ports:
      - "5001:5001"
    env_file:
      - ./server.env
    volumes:
      - ./server:/app/server
